Upload changed PDF's in batch
## Problem
The AWS Lambda function was throttled by Dropbox:

```
com.dropbox.core.RateLimitException: java.util.concurrent.ExecutionException
java.util.concurrent.ExecutionException: com.dropbox.core.RateLimitException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.s3dropbox.lambda.DbxFiles.$anonfun$uploadPdfs$2(DbxFiles.scala:32)
	at com.s3dropbox.lambda.DbxFiles.$anonfun$uploadPdfs$2$adapted(DbxFiles.scala:32)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at com.s3dropbox.lambda.DbxFiles.uploadPdfs(DbxFiles.scala:32)
	at com.s3dropbox.lambda.DossierMain.update(DossierMain.scala:18)
	at com.s3dropbox.lambda.DossierMain$.runDossier(DossierMain.scala:50)
	at com.s3dropbox.lambda.LambdaMain.handleRequest(LambdaMain.scala:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: com.dropbox.core.RateLimitException
	at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:383)
	at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:324)
	at com.dropbox.core.DbxUploader.finish(DbxUploader.java:268)
	at com.dropbox.core.DbxUploader.uploadAndFinish(DbxUploader.java:126)
	at com.dropbox.core.DbxUploader.uploadAndFinish(DbxUploader.java:96)
	at com.dropbox.core.v2.DbxUploadStyleBuilder.uploadAndFinish(DbxUploadStyleBuilder.java:92)
	at com.s3dropbox.lambda.DbxFiles.$anonfun$updatePdf$1(DbxFiles.scala:58)
	at com.s3dropbox.lambda.DbxFiles.$anonfun$updatePdf$1$adapted(DbxFiles.scala:53)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Solution
Use the Dropbox batch API to upload PDFs

## Test
Updated unit tests and tested end-2-end locally